---

apiVersion: v1
kind: Pod
metadata:
  name: storage-pod
spec:
  containers:
  - name: storage-container
    image: ubuntu:bionic
    command: ['sh', '-c', 'while /bin/true; do echo -n "still alive @ "; date; sleep 5; done']
    volumeMounts:
    - mountPath: /data
      name: host-data-pv
  volumes:
  - name: host-data-pv
    persistentVolumeClaim:
      claimName: storage-pvc
